### PR TITLE
TrustedScriptURL support for workbox-window

### LINKED ISSUE #2855: Trusted types support in workbox-window's register()
**Library Affected**:
workbox--window

**Browser & Platform**:
Any browser with support of CSP 2.0

**Issue or Feature Request Description**:
When installing the CSP policy "require-trusted-types-for 'script'" - the security error occurs in the browser

image

Usefull link : [Prevent DOM-based cross-site scripting vulnerabilities with Trusted Types](https://web.dev/trusted-types/)

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @tropicadri
CC: @budarin

Fixes #2855

This should be backwards compatible. At some point, if `TrustedScriptURL` is added to the TypeScript `lib.dom` library, we can remove the dependency on `@types/trusted-types`.

### CODE REVIEW

**Review by tropicadri — APPROVED** [review]

**Comment by cypressious** [comment]
After upgrading Workbox to 6.2.2 in my Vue project, I'm now getting a build error

```
 error  in Y:/Repos/xxx/Frontend/node_modules/workbox-window/Workbox.d.ts

ERROR in Y:/Repos/xxx/Frontend/node_modules/workbox-window/Workbox.d.ts(1,34):
1:34 Cannot find module 'trusted-types/lib' or its corresponding type declarations.
  > 1 | import { TrustedScriptURL } from 'trusted-types/lib';
      |                                  ^
    2 | import { WorkboxEventTarget } from './utils/WorkboxEventTarget.js';
    3 | import './_version.js';
    4 | /**
```

Is `@types/trusted-types` now a required dependency?

**Comment by jeffposnick** [comment]
I'm sorry about that—you're correct in that those type definitions should be listed in `dependencies` and not `devDependencies` to ensure that folks who install `workbox-window` from `npm` have also get the type defs.

This will be fixed in an upcoming v6.2.3 release, but in the meantime, you can explicitly add `@types/trusted-types` to your project if you're blocked on v6.2.2.

**Comment by jeffposnick** [comment]
This should be resolved in v6.2.3: https://github.com/GoogleChrome/workbox/releases/tag/v6.2.3
