### ISSUE TITLE
TypeError:  getFileManifestEntries is not a function

### ISSUE THREAD

**Issue by bpaduch** [GoogleChrome/workbox#1359]
**Library Affected**:
* workbox-build@3.0.0 
* workbox-sw@3.0.0 

**Browser & Platform**:
Chrome browser, gulp task

**Issue Description**:
Our gulp task fails with the following error **TypeError: swBuild.getFileManifestEntries is not a function** using `getFileManifestEntries` in this [gulp task](https://github.com/ampproject/docs/blob/master/gulpfile.js#L92).  This was working on the previous build (2.1.3).

What's changed?

Log from [Travis build](https://api.travis-ci.org/v3/job/353156575/log.txt):

```
[03:01:48] TypeError: swBuild.getFileManifestEntries is not a function
    at Gulp.<anonymous> (/home/travis/build/ampproject/docs/gulpfile.js:93:11)
    at module.exports (/home/travis/build/ampproject/docs/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/travis/build/ampproject/docs/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/travis/build/ampproject/docs/node_modules/orchestrator/index.js:214:10)
    at /home/travis/build/ampproject/docs/node_modules/orchestrator/index.js:279:18
    at finish (/home/travis/build/ampproject/docs/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/home/travis/build/ampproject/docs/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask (/home/travis/build/ampproject/docs/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/travis/build/ampproject/docs/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/travis/build/ampproject/docs/node_modules/orchestrator/index.js:134:8)
```

**Comment by jeffposnick** [comment]
Hello @bpaduch—I've filed https://github.com/google/WebFundamentals/pull/5911 to add some more info explicitly about this use case to the v2 to v3 migration guide. I hope that helps!

You could learn more about the updated interface is described at https://developers.google.com/web/tools/workbox/modules/workbox-build#getmanifest_mode and https://developers.google.com/web/tools/workbox/reference-docs/prerelease/module-workbox-build#.getManifest
